### PR TITLE
#98: Pike: Remove use of MPI_COMM_WORLD

### LINKED ISSUE #98: Pike: Remove the use of `MPI_COMM_WORLD`

### PR DESCRIPTION
**Pull request by thearusable**
Closes #98

### CODE REVIEW

**Review by JacobDomagala — DISMISSED** [review]

**Comment by stmcgovern** [comment]
Please explicitly invoke the namespace of the package

**Comment by thearusable** [comment]
@stmcgovern Ok, fixed.

**Comment by JacobDomagala** [comment]
Make sure the new header is installed properly

**Comment by thearusable** [comment]
@JacobDomagala New header is installed correctly.

**Review by JacobDomagala — APPROVED** [review]

**Comment by thearusable** [comment]
@stmcgovern - Looks like `Pike` package was removed from Trilinos: https://github.com/trilinos/Trilinos/tree/develop/packages

**Pull request merged**
