### PR TITLE
#187: Provide `Tpetra` version of BiCGStab examples

### LINKED ISSUE #187: Belos: Provide `Tpetra` version of BiCGStab example
Child issue of #158

### PR DESCRIPTION
**Pull request by cwschilly**
Fixes #187

### CODE REVIEW

**Comment by cwschilly** [comment]
@stmcgovern This PR is ready for review

**Review by antoinemeyer5 — COMMENTED** [review]
See 3 comments on #179 and after that LGTM

**Review by tlamonthezie — COMMENTED** [review]
Seems a duplicate of the test at tpetra/test/BiCGStab/test_bicgstab_hb

**Comment by cwschilly** [comment]
Per Jenn Loe's comment [here](https://github.com/NexGenAnalytics/Trilinos/issues/55#issuecomment-1703042362), this example is not required for conversion.

**Pull request closed without merging**
